//@version=5
indicator('X Trend INDICATOR', max_bars_back=200, overlay=true)

//inp_Amplitude = input(2, title = "Amplitude", type = input.integer)

Lowest_Low = ta.lowest(low, 3)
MA_Low = ta.ema(low, 3)

Highest_High = ta.highest(high, 2)
MA_High = ta.sma(high, 2)

Next_Trend = 0
Next_Trend := nz(Next_Trend[1], Next_Trend)

Trend = 0
Trend := nz(Trend[1], Trend)

Low_Max = low[1]
Low_Max := nz(Low_Max[1], Low_Max)

High_Min = high[1]
High_Min := nz(High_Min[1], High_Min)

if Next_Trend == 1
    Low_Max := math.max(Low_Max, Lowest_Low)
if MA_High < Low_Max and close < low[1]
    Trend := 1
    Next_Trend := 0
    High_Min := Highest_High
    High_Min

if Next_Trend == 0
    High_Min := math.min(High_Min, Highest_High)
if MA_Low > High_Min and close > high[1]
    Trend := 0
    Next_Trend := 1
    Low_Max := Lowest_Low
    Low_Max

Arrow_Shift = 0.0
Line_Color = color.gray

Line_HT = close
Line_HT := nz(Line_HT[1], Line_HT)

if Trend == 0
    Line_Color := color.blue
if Trend[1] == 0
    Line_HT := math.max(Low_Max, Line_HT[1])
    Line_HT
if Trend[1] == 1
    Arrow_Shift := -1 * ta.atr(10)
    Arrow_Shift

if Trend == 1
    Line_Color := color.orange
if Trend[1] == 1
    Line_HT := math.min(High_Min, Line_HT[1])
    Line_HT
if Trend[1] == 0
    Arrow_Shift := 1 * ta.atr(10)
    Arrow_Shift

//plot(Line_HT, color=color.new(Line_Color, 0), linewidth=2, title='X Trend')
//plot(ta.ema(close, 200), title='200 EMA', color=color.new(color.orange, 0), linewidth=2)
//plotshape(Arrow_Shift > 0 ? Line_HT + Arrow_Shift : na, style=shape.triangledown, location=location.absolute, color=color.new(Line_Color, 0), size=size.tiny)
//plotshape(Arrow_Shift < 0 ? Line_HT + Arrow_Shift : na, style=shape.triangleup, location=location.absolute, color=color.new(Line_Color, 0), size=size.tiny)

// Alerts
//alertcondition(Arrow_Shift < 0 ? Line_HT + Arrow_Shift : na, title='Long', message='Xtreme Trend Long')
///alertcondition(Arrow_Shift > 0 ? Line_HT + Arrow_Shift : na, title='Short', message='Xtreme Trend Short')

int decision = na
if Trend != Trend[1]
    if Trend == 1
        decision := 1
    else
        decision := -1

plotshape(series=decision == -1, title="Buy Signal", location=location.belowbar, color=color.green, style=shape.labelup, text="B")
plotshape(series=decision == 1, title="Sell Signal", location=location.abovebar, color=color.red, style=shape.labeldown, text="S")

// Alert conditions based on the decision variable
alertcondition(decision == -1, title='Long', message='Xtreme Trend Long')
alertcondition(decision == 1, title='Short', message='Xtreme Trend Short')